package com.elianfabian.bluetoothchatapp_prototype.home.di

import com.elianfabian.bluetoothchatapp_prototype.common.data.AccessFineLocationPermissionController
import com.elianfabian.bluetoothchatapp_prototype.common.data.BluetoothPermissionController
import com.elianfabian.bluetoothchatapp_prototype.common.data.MainActivityHolder
import com.elianfabian.bluetoothchatapp_prototype.common.di.lookupApplicationContext
import com.elianfabian.bluetoothchatapp_prototype.common.util.simplestack.CoroutineScopedServiceModule
import com.elianfabian.bluetoothchatapp_prototype.common.data.BluetoothControllerImpl
import com.elianfabian.bluetoothchatapp_prototype.common.data.PostNotificationsPermissionController
import com.elianfabian.bluetoothchatapp_prototype.common.domain.BluetoothController
import com.elianfabian.bluetoothchatapp_prototype.home.presentation.HomeViewModel
import com.zhuinden.simplestack.ServiceBinder
import com.zhuinden.simplestackextensions.servicesktx.add
import com.zhuinden.simplestackextensions.servicesktx.lookup

data object HomeModule : CoroutineScopedServiceModule() {

	override fun bindModuleServices(serviceBinder: ServiceBinder) {

	}
}
